### ISSUE TITLE
Migrate to a newer crypto dependency

### ISSUE THREAD

**Issue by Pavinati** [sagarkhan/astarte-device-sdk#3]
Right now `ecdsa-secp256r1` is used to generate certificate sign request, but this dependency last release was more than 3 years ago and doesn't seem quite popular on the npm community (14 starts on GitHub).
I suggest using `node-forge` which releases more often and is widely used (4k stars and 100k+ weekly downloads).

**Comment by sagarkhan** [comment]
@Pavinati, Initially i used node-forge, but it has following drawbacks

- node-forge is a heavy library
- It does not supports secp256k1/secp256r1 (ECDSA) certificates.  [Issue](https://github.com/digitalbazaar/forge/issues/580)
- Alternatively if we use RSA it consumes more computation. 

However node-forge do supports ed25519 certificates, let me know if thats good as per Astarte's standards
