### ISSUE TITLE
Fix interface validation

### ISSUE THREAD

**Issue by davidebriani** [sagarkhan/astarte-device-sdk#5]
Interface validation with Joi is erroring on [Astarte standard interfaces](https://github.com/astarte-platform/astarte/blob/master/standard-interfaces/) such as `org.astarte-platform.genericsensors.Values`. It would be nice if these interfaces could work as-is.

**Comment by sagarkhan** [comment]
This is fixed, it was because `description` and `doc` fields were not added in the validations schema, since we are following strict validations all the interface fields should be part of Joi schema

https://github.com/sagarkhan/astarte-device-sdk/blob/master/src/utils/validator.ts#L69
